### PR TITLE
[COMPLIANCE] launch a daily task to correct item which reached compli…

### PR DESCRIPTION
**Pull request by jerome-poisson**
…ance EOL

A task is launched everyday to correct item which have just reached compliance end-of-life
(i.e. they expire "today"). The settings's COMPLIANCE_EOL_TEXT is prepended to body.

SDFID-586

### CODE REVIEW

**Comment by jerome-poisson** [comment]
The script is working, but I'm adding `WIP` label because the `body_html` correction is not visible in client except if I delete `fields_meta`.

**Comment by tomaskikutis** [comment]
If you delete `fields_meta.body_html`, many things might break when updating the article. Annotations will probably disappear, media metadata won't be editable, tables might break, etc.

You need to update both - `body_html` and `fields_meta.body_html`. The correct way to do it would be to set up `nodejs` on the server and reuse editor3 code to modify `body_html` so you don't have to make assumptions about what the client will generate.

Of course, that would take quite some effort, and you could instead try a workaround which is to patch `fields_meta.body_html`. If you only want to add a plain text paragraph, it should be easy and safe to patch. I could provide you a JSON block to insert.

**Comment by jerome-poisson** [comment]
using `nodejs` in the backend is clearly not an option. And patching `field_meta` is wrong too, we must not depend on implementation specific data. Let's discuss about that in the right ticket (https://dev.sourcefabric.org/browse/SDESK-4799).

**Comment by jerome-poisson** [comment]
note: for now the `body_html` is modified directly, with the aforementioned issue that the client will show the former body. After checking with @hlmnrmr it's fine for a first version, and I'll add draftjs support later once https://dev.sourcefabric.org/browse/SDESK-4799 is merged.

**Comment by jerome-poisson** [comment]
@ride90 I've added a test

**Pull request merged**
