### PR TITLE
Override login and hide form

### PR DESCRIPTION
**Pull request by pablopunk**
SDFID-357

Depends on https://github.com/superdesk/superdesk-client-core/pull/2835

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Creating a custom login template is fine, but what I don't like is that there's too much logic in the template(for example instead of errors placeholder it lists every possible error), that forgot password page is put in the same place and most of all that it uses a controller from the client.

If it didn't use the core controller, the code would still be not ideal, but at least it would not be dependent on the core login controller.

Another solution could be keeping the original template in the core, and passing a parameter additionalLinks where you could add your "back to SSO" link. You would also need another parameter showCustomLogin which when true, original login would hide and you could show a custom one.

**Comment by pablopunk** [comment]
@tomaskikutis but the template is basically the same, it should use the same controller. The only thing it does is hiding the form and show the SSO button, but everything else should be same (except for the disabled logins: google, etc). The alternative would be writing even more logic on the core modal

**Comment by tomaskikutis** [comment]
I meant to suggest to copy the controller from the client to fi repo and change what you need. If you are depending on the client controller it makes the code no more modular than if SSO logic were in the core. It would even be easier to maintain if it was in the core because you could see all the use cases in one file.

The ideal solution would be exposing simple public API methods similar to this, so you don't need to depend on the client controller.
```
interface IStatusMessages {
    messages: Array<string>;
}

interface ILoginPage {
    attemptLogin: (username, password) => Promise<IStatusMessages>;
    resetPassword: (email) => Promise<IStatusMessages>;
}
```

This might be too much work for now that's why I suggest to copy the controller so changes on the client don't break this page.

**Comment by pablopunk** [comment]
> I meant to suggest to copy the controller from the client to fi repo and change what you need.

I guess you mean the directive.

I can do that but I don't think it would be a good idea cause I would duplicate a lot of code from the client. This page is just a view for what IMO should be the same directive (login-directive). I override it just to hide some inputs. If the directive changes in the future affecting this view, we probably do want those changes to affect it (even tho we need to change something here). Otherwise if we need to change something on the directive here we'll need to update the directive in both repos with probably the same code.

**Comment by pablopunk** [comment]
I also agree we shouldn't duplicate error view and stuff like that but I think that could be another ticket for the core, not this repo

**Comment by tomaskikutis** [comment]
Duplicating the code from the client is not good, but I'd argue it's a lesser evil compared to creating coupling between logic in the core(directive) and a **template in a separate repository**.

I think you should either duplicate the directive too or do a proper solution by creating a loginService which would act as a public API and encapsule most of the logic from current login directive. You could then use the service in both the core and the this repo.

**Comment by pablopunk** [comment]
@tomaskikutis can you override a directive on demand?

**Comment by tomaskikutis** [comment]
No idea. I assume you could set a flag and not register it in the core in the first place.

**Comment by tomaskikutis** [comment]
Update the comment adding that it's a **modified** copy. Maintanence instructions need to be added to the comment too. There's now no way for a developer to know if files need to be kept in sync or copying was a fork and files are now developed independently.

**Pull request merged**
